# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateAndTimePlanned', models.DateTimeField(null=True)),
                ('clientId', models.IntegerField(null=True)),
                ('datePlanned', models.DateTimeField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('employeeId', models.IntegerField(null=True)),
                ('formGroupId', models.IntegerField(null=True)),
                ('groupId', models.IntegerField(null=True)),
                ('locationCode', models.CharField(max_length=200, null=True)),
                ('locationDescription', models.CharField(max_length=200, null=True)),
                ('locationId', models.IntegerField(null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('plannerGroupId', models.IntegerField(null=True)),
                ('plannerId', models.IntegerField(null=True)),
                ('programCode', models.CharField(max_length=200, null=True)),
                ('programDescription', models.CharField(max_length=200, null=True)),
                ('programId', models.IntegerField(null=True)),
                ('timePlanned', models.DateTimeField(null=True)),
                ('visitStatus', models.CharField(max_length=200, null=True)),
                ('visitTypeDescription', models.CharField(max_length=200, null=True)),
                ('visitTypeFormId', models.IntegerField(null=True)),
                ('visitTypeId', models.IntegerField(null=True)),
                ('visitTypeLabel', models.CharField(max_length=200, null=True)),
                ('weekOfTime', models.DateTimeField(null=True)),
            ],
        ),
    ]
