# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160409145743 on 2016-04-10 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20160410_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergies',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Profile'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='allergies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Allergies'),
        ),
        migrations.AddField(
            model_name='medications',
            name='Contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Contacts'),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='dateCreated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='allergies',
            name='dateUpdated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='dateCreated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='dateReleasedInfoExpires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='dateReleasedInfoStarts',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='dateUpdated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='dateChanged',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='dateCreated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='dateDiscontinued',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='dateStarted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medications',
            name='dateUpdated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='admissionDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='assessmentDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dateOfBirth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dischargeDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstBillSVCDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstSVCDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intakeDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastBillSVCDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastSVCDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referralDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='statusDate',
            field=models.DateTimeField(null=True),
        ),
    ]
